class PagesController < ApplicationController
  def home
    # CREATED OUTSIDE NORMAL RESTFUL CONVENTION FOR HOMEPAGE SEPARATING
    # AUTH ACTIONS
    # EXITS IN ROUTE ONLY NEEDED TO RENDER VIEW NO LOGIC
  end
end
